version: '3.8'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www/html

  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 8080:80